version: '3.3'
services:
  db:
    container_name: db
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql
  spring_app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - IMAGE_NAME=benaissa007/detailequipe
    container_name: back
    restart: on-failure
    ports:
      - 9091:9091
    depends_on:
      - db
    command: sh -c "docker push benaissa007/detailequipe"